agent {
  data_dir = "/run/spire/agent-data"
  log_level = "INFO"
  server_address = "spire-server"
  server_port = "8081"
  socket_path = "/run/spire/agent-sockets/spire-agent.sock"
  trust_domain = "airlock.local"
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "disk" {
    plugin_data {
      directory = "/run/spire/agent-data"
    }
  }

  WorkloadAttestor "unix" {
    plugin_data {}
  }
}
