apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-provider-config.yaml
  - policy.yaml
  - workload.yaml
  - envoy-config.yaml
  - echo-upstream.yaml
  - proxy-worker.yaml
  - code-agent.yaml

generatorOptions:
  disableNameSuffixHash: true

