apiVersion: airlock.dev/v1alpha1
kind: SecretProviderConfig
metadata:
  name: default-vault
  namespace: airlock-system
spec:
  provider: vault
  vault:
    address: http://vault.vault.svc.cluster.local:8200
    auth:
      method: spiffe-jwt
      mount: jwt
      audience: vault
    defaults:
      engine: kv-v2
      mount: secret
      pathPrefix: dev
