apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/airlock.dev_secretproviderconfigs.yaml
  - crds/airlock.dev_airlockpolicies.yaml
  - crds/airlock.dev_airlockworkloads.yaml
  - namespaces.yaml
  - spire-system/airlock-spiffe-ids.yaml
  - airlock-system/control-plane-rbac.yaml
  - airlock-system/webhook-tls.yaml
  - airlock-system/control-plane-skeleton.yaml
  - airlock-system/injection-webhook.yaml
  - vault/vault-dev.yaml

generatorOptions:
  disableNameSuffixHash: true
