apiVersion: v1
kind: Namespace
metadata:
  name: airlock-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: spire-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    airlock.dev/injection: enabled
