# syntax=docker/dockerfile:1

FROM ghcr.io/spiffe/spire-server:1.12.4 AS server
FROM ghcr.io/spiffe/spire-agent:1.12.4 AS agent

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=server /opt/spire/bin/spire-server /usr/local/bin/spire-server
COPY --from=agent /opt/spire/bin/spire-agent /usr/local/bin/spire-agent
